---
- hosts: all
  become: true
  vars:
    container_count: 4
    default_container_name: docker
    default_container_image: ubuntu
    default_container_command: sleep 1d
    jenkins_dir: /opt/jenkins_custom
    jenkins_prefix: /jenkins
    jenkins_port: 8080

  tasks:
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
          - python3.12-venv
        state: latest
        update_cache: true

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Create virtual environment
      ansible.builtin.command: python3 -m venv /opt/myenv

    - name: Install docker in venv
      ansible.builtin.command: /opt/myenv/bin/pip install docker

    - name: Pull default Docker image
      community.docker.docker_image:
        name: "{{ default_container_image }}"
        source: pull
    - name: Install latest Java (21)
      apt:
        name: openjdk-21-jdk
        state: present
      ignore_errors: yes

    - name: Fallback to Java 17 if needed
      apt:
        name: openjdk-17-jdk
        state: present
      when: ansible_failed_result is defined

    - name: Create Jenkins install directory
      file:
        path: "{{ jenkins_dir }}"
        state: directory
        mode: '0755'

    - name: Download Jenkins WAR file
      get_url:
        url: https://get.jenkins.io/war-stable/latest/jenkins.war
        dest: "{{ jenkins_dir }}/jenkins.war"
        mode: '0755'

    - name: Create Jenkins systemd service with /jenkins prefix
      copy:
        dest: /etc/systemd/system/jenkins-custom.service
        content: |
          [Unit]
          Description=Jenkins Custom Service
          After=network.target

          [Service]
          User=root
          ExecStart=/usr/bin/java -jar {{ jenkins_dir }}/jenkins.war --httpPort={{ jenkins_port }} --prefix={{ jenkins_prefix }}
          SuccessExitStatus=143
          TimeoutStopSec=5
          Restart=on-failure
          RestartSec=10

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Enable and start Jenkins custom
      systemd:
        name: jenkins-custom
        enabled: yes
        state: started
